services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 5
      ZOOKEEPER_SYNC_LIMIT: 2
      ZOOKEEPER_MAX_CLIENT_CNXNS: 60
      ZOOKEEPER_4LW_COMMANDS_WHITELIST: ruok,mntr,conf,stat
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka1:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics",
          "--bootstrap-server",
          "localhost:9092",
          "--list",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka2:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:29093,PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics",
          "--bootstrap-server",
          "localhost:9093",
          "--list",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka3:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:29094,PLAINTEXT_HOST://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx256M -Xms128M"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics",
          "--bootstrap-server",
          "localhost:9094",
          "--list",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka1:29092,kafka2:29093,kafka3:29094
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Cassandra Database
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: finnhub_cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      MAX_HEAP_SIZE: "512M"
      HEAP_NEWSIZE: "128M"
      CASSANDRA_ENDPOINT_SNITCH: SimpleSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q '^UN'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Cassandra Init Script Runner
  cassandra-init:
    image: cassandra:4.0
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./init-scripts:/init-scripts
    command: >
      bash -c "
        echo 'Waiting for Cassandra to be ready...' &&
        until cqlsh cassandra -e 'DESCRIBE KEYSPACES;'; do
          echo 'Cassandra is unavailable - sleeping'
          sleep 2
        done &&
        echo 'Cassandra is up - executing init scripts' &&
        cqlsh cassandra -f /init-scripts/init-cassandra.cql &&
        echo 'Initialization completed!' &&
        sleep infinity"
    deploy:
      resources:
        limits:
          memory: 256M
    restart: on-failure

  # Kafka topic initializer
  kafka-topic-init:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Waiting for Kafka to be ready...' &&
        sleep 10 &&
        echo 'Creating Kafka topics...' &&
        kafka-topics --bootstrap-server kafka1:29092 --create --if-not-exists --topic finnhub_trades --partitions 6 --replication-factor 3 --config cleanup.policy=delete --config retention.ms=604800000 &&
        echo 'Topic created. Checking details:' &&
        kafka-topics --bootstrap-server kafka1:29092 --describe --topic finnhub_trades &&
        echo 'Kafka topic initialization completed!' &&
        exit 0"
    deploy:
      resources:
        limits:
          memory: 256M
    restart: on-failure

  # Producer cho dữ liệu thời gian thực từ Finnhub WebSocket
  finnhub-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - FINNHUB_API_TOKEN=${FINNHUB_API_TOKEN}
      - KAFKA_SERVER=kafka1
      - KAFKA_PORT=29092
      - KAFKA_TOPIC_NAME=finnhub_trades
      - FINNHUB_STOCKS_TICKERS=["BINANCE:BTCUSDT", "BINANCE:ETHUSDT", "BINANCE:BNBUSDT", "BINANCE:ADAUSDT", "BINANCE:XRPUSDT", "BINANCE:SOLUSDT", "BINANCE:DOGEUSDT", "BINANCE:MATICUSDT", "BINANCE:DOTUSDT", "BINANCE:LINKUSDT"]
      - FINNHUB_VALIDATE_TICKERS=1
      - KAFKA_NUM_PARTITIONS=6
      - KAFKA_REPLICATION_FACTOR=3
    depends_on:
      kafka1:
        condition: service_healthy
      kafka-topic-init:
        condition: service_completed_successfully
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    # profiles: ["real-time"] # Chỉ chạy khi chọn profile real-time

  spark-master:
    image: bitnami/spark:3.4.1
    ports:
      - "8080:8080" # Spark Master UI
      - "7077:7077" # Spark Master port
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - spark_logs:/opt/bitnami/spark/logs
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  spark-worker-1:
    image: bitnami/spark:3.4.1
    depends_on:
      spark-master:
        condition: service_healthy
    ports:
      - "8081:8081" # Spark Worker 1 UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - spark_logs:/opt/bitnami/spark/logs
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  spark-worker-2:
    image: bitnami/spark:3.4.1
    depends_on:
      spark-master:
        condition: service_healthy
    ports:
      - "8082:8081" # Spark Worker 2 UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - spark_logs:/opt/bitnami/spark/logs
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  spark-app:
    build:
      context: ./processor
      dockerfile: Dockerfile
    depends_on:
      spark-master:
        condition: service_healthy
      kafka1:
        condition: service_healthy
      kafka2:
        condition: service_healthy
      kafka3:
        condition: service_healthy
      cassandra-init:
        condition: service_completed_successfully
      kafka-topic-init:
        condition: service_completed_successfully
    ports:
      - "4040:4040" # Spark UI
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - KAFKA_BOOTSTRAP_SERVERS=kafka1:29092,kafka2:29093,kafka3:29094
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - KAFKA_TOPIC_NAME=finnhub_trades
    command: >
      bash -c "
        echo 'Waiting for Spark Master to be ready...' &&
        until curl -f http://spark-master:8080 >/dev/null 2>&1; do
          echo 'Spark Master not ready yet - sleeping'
          sleep 2
        done &&
        echo 'Waiting for Cassandra initialization to complete...' &&
        sleep 10 &&
        echo 'Spark Master is up - starting application' &&
        cd /app && 
        spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1,com.datastax.spark:spark-cassandra-connector_2.12:3.4.0 --conf spark.cassandra.connection.host=cassandra --conf spark.cassandra.auth.username=cassandra --conf spark.cassandra.auth.password=cassandra processor.py"
    volumes:
      - ./processor:/app
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  cassandra-web:
    image: ipushc/cassandra-web
    ports:
      - "8083:8083"
    environment:
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    depends_on:
      cassandra-init:
        condition: service_completed_successfully
    restart: on-failure:3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8083"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  spark_logs:
  cassandra_data:
  grafana_data:
