services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics",
          "--bootstrap-server",
          "localhost:9092",
          "--list",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  kafdrop:
    image: obsidiandynamics/kafdrop:latest
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: kafka:29092
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  # Cassandra Database
  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: finnhub_cluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      MAX_HEAP_SIZE: "512M"
      HEAP_NEWSIZE: "128M"
      CASSANDRA_ENDPOINT_SNITCH: SimpleSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "nodetool status | grep -q '^UN'"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  # Cassandra Init Script Runner
  cassandra-init:
    image: cassandra:4.0
    depends_on:
      cassandra:
        condition: service_healthy
    volumes:
      - ./init-scripts:/init-scripts
    command: >
      bash -c "
        echo 'Waiting for Cassandra to be ready...' &&
        until cqlsh cassandra -e 'DESCRIBE KEYSPACES;'; do
          echo 'Cassandra is unavailable - sleeping'
          sleep 2
        done &&
        echo 'Cassandra is up - executing init scripts' &&
        cqlsh cassandra -f /init-scripts/init-cassandra.cql &&
        echo 'Initialization completed!' &&
        sleep infinity"
    deploy:
      resources:
        limits:
          memory: 256M
    restart: on-failure

  # Chọn một trong hai producer (không nên chạy cả hai cùng lúc)

  # Producer cho dữ liệu thời gian thực từ Finnhub WebSocket
  finnhub-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    environment:
      - FINNHUB_API_TOKEN=${FINNHUB_API_TOKEN}
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
      - KAFKA_TOPIC_NAME=finnhub_trades
      - FINNHUB_STOCKS_TICKERS=["D05.SI", "O39.SI", "AAPL"]
      - FINNHUB_VALIDATE_TICKERS=1
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    restart: unless-stopped
    profiles: ["real-time"] # Chỉ chạy khi chọn profile real-time

  # Producer cho dữ liệu lịch sử giả lập
  historical-producer:
    build:
      context: ./producer
      dockerfile: Dockerfile.historical
    environment:
      - FINNHUB_API_TOKEN=${FINNHUB_API_TOKEN}
      - KAFKA_SERVER=kafka
      - KAFKA_PORT=29092
      - KAFKA_TOPIC_NAME=finnhub_trades
      - FINNHUB_STOCKS_TICKERS=["AAPL", "MSFT", "GOOGL"]
      - HISTORICAL_RESOLUTION=1
      - HISTORICAL_DAYS_BACK=7
      - SIMULATION_SPEED=1000
      - TRADES_PER_CANDLE=5
    depends_on:
      kafka:
        condition: service_healthy
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    profiles: ["simulation"] # Chỉ chạy khi chọn profile simulation

  spark-master:
    image: bitnami/spark:3.4.1
    ports:
      - "8080:8080" # Spark Master UI
      - "7077:7077" # Spark Master port
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8080
    volumes:
      - spark_logs:/opt/bitnami/spark/logs
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5

  spark-worker:
    image: bitnami/spark:3.4.1
    depends_on:
      spark-master:
        condition: service_healthy
    ports:
      - "8081:8081" # Spark Worker UI
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_MEMORY=1G
      - SPARK_WORKER_CORES=2
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - spark_logs:/opt/bitnami/spark/logs
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  spark-app:
    build:
      context: ./processor
      dockerfile: Dockerfile
    depends_on:
      spark-master:
        condition: service_healthy
      kafka:
        condition: service_healthy
      cassandra-init:
        condition: service_completed_successfully
    ports:
      - "4040:4040" # Spark UI
    environment:
      - SPARK_MASTER_URL=spark://spark-master:7077
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
      - SPARK_DRIVER_MEMORY=512m
      - SPARK_EXECUTOR_MEMORY=512m
      - SPARK_UI_PORT=4040
    command: >
      bash -c "
        echo 'Waiting for Spark Master to be ready...' &&
        until curl -f http://spark-master:8080 >/dev/null 2>&1; do
          echo 'Spark Master not ready yet - sleeping'
          sleep 2
        done &&
        echo 'Waiting for Cassandra initialization to complete...' &&
        sleep 10 &&
        echo 'Spark Master is up - starting application' &&
        cd /app && 
        spark-submit --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.4.1,com.datastax.spark:spark-cassandra-connector_2.12:3.4.0 --conf spark.sql.extensions=com.datastax.spark.connector.CassandraSparkExtensions --conf spark.cassandra.connection.host=cassandra --conf spark.cassandra.connection.port=9042 --conf spark.cassandra.auth.username=cassandra --conf spark.cassandra.auth.password=cassandra processor.py"
    volumes:
      - ./processor:/app
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  cassandra-web:
    image: ipushc/cassandra-web
    ports:
      - "8083:8083"
    environment:
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_PORT=9042
      - CASSANDRA_USERNAME=cassandra
      - CASSANDRA_PASSWORD=cassandra
    depends_on:
      cassandra-init:
        condition: service_completed_successfully
    restart: on-failure:3
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:8083"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  spark_logs:
  cassandra_data:
